# Generated by Django 4.2.2 on 2023-06-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_chef_alter_contact_options_alter_gallery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='photo',
            field=models.ImageField(blank=True, upload_to='chefs/'),
        ),
    ]
