# Generated by Django 4.2.2 on 2023-06-29 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_chef_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ful_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +380xxxxxxxxx or 0xxxxxxxxx', regex='^(\\+38)?0[0-9]{9}$')])),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('of_people', models.PositiveSmallIntegerField(default=1)),
                ('message', models.TextField(blank=True, max_length=200)),
                ('is_processed', models.BooleanField(default=False)),
                ('date_in', models.DateTimeField(auto_now_add=True)),
                ('date_modify', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-date_in',),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True, max_length=200)),
                ('date_in', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_in',),
            },
        ),
    ]
