# Generated by Django 4.2.2 on 2023-07-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_booking_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='menu item')),
                ('slug', models.SlugField(unique=True, verbose_name='url')),
                ('position', models.PositiveSmallIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('name',), 'verbose_name_plural': 'Gallery'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=models.ImageField(blank=True, upload_to='gallery/'),
        ),
    ]
